export const users = [
  {
    id: 1,
    firstname: "Thomas",
    lastname: "Heuer",
    age: 37,
    email: "thommyH@aol.com",
    interessedIn: ["Fussball", "Fitness", "Party"],
    friends: ["Nicole Gruber", "Andreas Schrick", "Jochen Möller", "Lisa Müller"],
  },
  {
    id: 2,
    firstname: "Nicole",
    lastname: "Gruber",
    age: 33,
    email: "niciG@web.de",
    interessedIn: ["Fitness", "LaserTec"],
    friends: ["Thomas Heuer", "Andreas Schrick", "Christian Groth", "Lisa Müller"],
  },
  {
    id: 3,
    firstname: "Andreas",
    lastname: "Schrick",
    age: 35,
    email: "andiS@gmx.de",
    interessedIn: ["LasterTec", "Fussball", "Party"],
    friends: ["Nicole Gruber", "Thomas Heuer", "Jochen Möller", "Lisa Müller"],
  },
  {
    id: 4,
    firstname: "Jochen",
    lastname: "Möller",
    age: 34,
    email: "jomoeller@gmail.com",
    interessedIn: ["Party", "Fussball"],
    friends: ["Nicole Gruber", "Andreas Schrick", "Thomas Heuer", "Lisa Müller"],
  },
  {
    id: 5,
    firstname: "Lisa",
    lastname: "Müller",
    age: 28,
    email: "lism@gmail.com",
    interessedIn: ["Eislauf", "Hockey"],
    friends: ["Nicole Gruber", "Andreas Schrick", "Jochen Möller", "Thomas Heuer", "Miriam Jansen", "Christian Groth"],
  },
  {
    id: 6,
    firstname: "Miriam",
    lastname: "Jansen",
    age: 31,
    email: "mini31@gmx.de",
    interessedIn: ["Feuerwehr", "Party", "Chatten"],
    friends: ["Lisa Möller", "Christian Groth", "Thomas Friedrichs"],
  },
  {
    id: 7,
    firstname: "Christian",
    lastname: "Groth",
    age: 27,
    email: "chrischiii27@hotmail.com",
    interessedIn: ["Spieleabend", "Feuerwehr", "Netflix"],
    friends: ["Miriam Jansen", "Andreas Dietrich", "Lisa Wolf"],
  },
  {
    id: 8,
    firstname: "Natascha",
    lastname: "Cauz",
    age: 41,
    email: "nataCauz@freenet.de",
    interessedIn: ["Motorrad", "tanzen", "reisen"],
    friends: ["Nicole Jürgens", "Dirk Dietrichs", "Thomas Friedrichs"],
  },
  {
    id: 9,
    firstname: "Dirk",
    lastname: "Dietrichs",
    age: 43,
    email: "dd-rich@gmail.com",
    interessedIn: ["Autos", "tanzen", "Party"],
    friends: ["Natascha Cauz", "Nicole Jürgens"],
  },
  {
    id: 10,
    firstname: "Andreas",
    lastname: "Dietrich",
    age: 25,
    email: "andi25@gmx.com",
    interessedIn: ["Party", "Karaoke", "standup Paddling"],
    friends: ["Christian Groth", "Lisa Wolf", "Thomas Friedrichs"],
  },
  {
    id: 11,
    firstname: "Lisa",
    lastname: "Wolf",
    age: 23,
    email: "wolfsgirl@web.de",
    interessedIn: ["Party", "reisen", "Karaoke"],
    friends: ["Andreas Dietrich", "Christian Groth"],
  },
  {
    id: 12,
    firstname: "Thomas",
    lastname: "Friedrichs",
    age: 33,
    email: "thomasFriedrichs@gmail.com",
    interessedIn: ["Netflix", "Kino", "Party"],
    friends: ["Miriam Jansen", "Andreas Dietrich", "Natascha Cauz"],
  },
  {
    id: 13,
    firstname: "Nicole",
    lastname: "Jürgens",
    age: 39,
    email: "juergensNicole@gmail.com",
    interessedIn: ["reisen", "lesen", "tanzen"],
    friends: ["Natascha Cauz", "Dirk Dietrichs"],
  },
];